name: Post-PR Merge Thank You

on:
  pull_request:
    types: [closed]  # This will trigger the workflow when a PR is closed

permissions:
  issues: write
  pull-requests: write


jobs:
  post_merge_message:
    if: github.event.pull_request.merged == true  # Only run if the PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Post thank you message
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Post a cute thank you message
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: prNumber,
              body: `🎉🎉 Thank you for your contribution! Your PR has been merged !🎉🎉`
            });
